menu background /splash.bmp
LABEL Default
  LINUX /Image
  INITRD /initrd.img
  FDTDIR /dtb
  APPEND ${rootdev} rw rootfstype=ext4 rootwait fsck.mode=force fsck.repair=yes no_console_suspend consoleblank=0 earlycon=meson,0xfe078000,921600n8 keep_bootcon ignore_loglevel loglevel=8 oops=panic panic=0 clk_ignore_unused pd_ignore_unused 8250.nr_uarts=0 khadas_board=TVPRO cma=256M hdr_policy=1 cpuidle.off=1 nohz=off ${consoles} ${partitiontype} fan=${fan_mode} ${boot_user_args}

LABEL Recovery
  LINUX /boot/recovery/Image
  INITRD /boot/recovery/initrd.img
  FDTDIR /boot/recovery/dtb
  APPEND ${rootdev} rdinit=/init no_console_suspend consoleblank=0 earlycon=meson,0xfe078000,921600n8 keep_bootcon ignore_loglevel loglevel=8 clk_ignore_unused pd_ignore_unused 8250.nr_uarts=0 khadas_board=TVPRO fenix_recovery=1 fenix_ram_recovery=1 panic=0 cpuidle.off=1 nohz=off module_blacklist=aml_drm,aml_media,amlogic-power,amlogic-cpuinfo,amlogic-secmon ${consoles} ${partitiontype} fan=${fan_mode}

timeout 5
default Default
