menu background /splash.bmp
LABEL Recovery
  LINUX /boot/recovery/Image
  INITRD /boot/recovery/initrd.img
  FDT /boot/recovery/dtb/amlogic/amlogic-t7-a311d2-tvpro.dtb
  APPEND ${rootdev} rootflags=data=writeback rw rootfstype=ext4 rootwait no_console_suspend earlycon ignore_loglevel loglevel=8 8250.nr_uarts=0 khadas_board=TVPRO fenix_recovery=1 systemd.unit=multi-user.target panic=10 ${consoles} ${partitiontype} fan=${fan_mode}

timeout 1
default Recovery
