menu background /splash.bmp
LABEL Default
  LINUX /Image
  INITRD /initrd.img
  FDT /dtb/amlogic/amlogic-t7-a311d2-khadas-vim4.dtb
  APPEND ${rootdev} rootflags=data=writeback rw rootfstype=ext4 rootwait no_console_suspend earlycon ignore_loglevel loglevel=8 oops=panic panic=10 8250.nr_uarts=0 khadas_board=VIM4 ${consoles} ${partitiontype} fan=${fan_mode} ${boot_user_args}

LABEL Recovery
  LINUX /boot/recovery/Image
  INITRD /boot/recovery/initrd.img
  FDT /boot/recovery/dtb/amlogic/amlogic-t7-a311d2-khadas-vim4.dtb
  APPEND ${rootdev} rdinit=/init no_console_suspend earlycon ignore_loglevel loglevel=8 8250.nr_uarts=0 khadas_board=VIM4 fenix_recovery=1 fenix_ram_recovery=1 panic=10 module_blacklist=aml_drm,aml_media,amlogic-power,amlogic-cpuinfo,amlogic-secmon ${consoles} ${partitiontype} fan=${fan_mode}

timeout 5
default Default
